<?php 
$this->title = "Users";
$this->headTitle($this->title);
?>
 
 
<table>
<tr>
 <th>ID</th>
 <th>User name</th>
 <th>Email</th>
 <th>Password</th>
 <th>Role</th>
 <th>&nbsp;</th>
</tr>
<?php foreach($this->users as $user) : ?>
<tr>
 <td><?php echo $this->escape($user->id);?></td>
 <td><?php echo $this->escape($user->username);?></td>
 <td><?php echo $this->escape($user->email);?></td>
 <td><?php echo $this->escape($user->password);?></td>
 <td><?php echo $this->escape($user->role);?></td>
 <td>
 <a href="<?php echo $this->url(array('controller'=>'users',
 'action'=>'delete', 'id'=>$user->id));?>">Delete</a>
 </td>
</tr>
<?php endforeach; ?>
</table>
